
version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cmms
      - NODE_ENV=production
      - SESSION_SECRET=your_secure_random_string_here
      - HOST=0.0.0.0
      - PORT=5000
      # Set FORCE_DB_REBUILD=true for initial deployment, then set to false after first successful deployment
      # WARNING: Setting this to true will erase all database data
      - FORCE_DB_REBUILD=false
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cmms-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cmms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cmms-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - cmms-network

volumes:
  postgres_data:

networks:
  cmms-network:
    driver: bridge
